name: Product API

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["10", "12"]
    steps:
      - uses: actions/checkout@v1
      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test

  build_publish_docker:
    name: Build & Publish Docker Image to ECR
    runs-on: ubuntu-latest
    needs: ["test"]
    env:
      REPO: ${{ secrets.DOCKER_ECR_REPO }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to AWS ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username ${{ secrets.DOCKER_ECR_USERNAME }} --password-stdin $REPO
      - name: Build Docker image
        run: docker build -t $REPO/produtos-api:latest -t $REPO/produtos-api:${GITHUB_SHA::8} .
      - name: Push to ECR
        run: docker push $REPO/produtos-api

  
